---
title: "2024年にやった逸般的なこと"
subtitle: "みすてむず いず みすきーしすてむず Advent Calendar 2024"
date: 2023/12/30
format:
    html:
        toc: true
---

# Title

~~この期に及んで未だに迷走している~~

いつもお世話になっております。epsilonです

えーと、まずは謝罪からなのですが原稿遅れて申し訳ございません。 しかも、遅れた上に自分語りかよって話で本当に申し訳ありません。

自分語りではありますが、非園児猫の私が（みすてむずに看過されて）行った IT関係の記録を残しておくと、もしかすると誰かの参考にもなるかなと思って書いてみました。 なにかの暇つぶしにでもなれば幸いです。

なお、本記事は[みすてむず いず みすきーしすてむず Advent Calendar 2024](https://adventar.org/calendars/10203)の12月14日分の記事です（でした)


## 1. Interop見学

2024年のイベントで一番逸般なのがこれでした。

まずInteropというイベントを知ったのが結構ぎりぎりだったような？某有名逸般の誤家庭Youtuber氏の動画見てInteropというイベントを知り、これだけ多くのベンダーが一同に介してでっかいネットワークを作るなんて絶対楽しいやつやん！！と思って参加してきました。 急に休みとって上司に軽く怒られたような気がしなくもない。

幕張メッセのホールにサーバー群が立ってるのも興奮しましたし、NOCをみるのも初めてだったので単純に「かっけー！！！」って思っていました。IOWNの低遅延通信は本当に目の前に人がいるかのような感覚がありましたし、Interop会場がリアルタイムに数万件の不正アクセスを受けている(そしてそれを防いでいる）のも衝撃的でしたし、なにより今まで漠然としか捉えていなかった「インターネット」「ネットワーク」を作るってこういうことなんだなというのを目の当たりにしたのは、大変に面白かったです。

企業ブースを中心に回ったせいか結構しっかりとビジネスの展示会だなという印象が強いんですが（そりゃ個人で買うやつなんかごく一部でしょうから当然ではありますが）一方で、業務レベルでネットワークを考えるときはこういうことをするんだなというのは非専門職にとってはいい勉強になりました。まぁ、数百万クラスの製品を売り込まれても、とても買えやしないので申し訳ねぇなとは思いましたけど……

Interopで展示されているのは10年後、20年後のインターネットの姿だといいますが、あと10年ほどしたらIOWNが当たり前になっていくんですかね？

## 2. データ処理の講習会

これはオシゴト絡みの講習会なんですが、機会があって、大規模データの扱い方・まとめ方を学べる講習会に参加していました。約半年コースで毎週末に講義＆実習＋宿題ありだったので、オシゴトしながら受講するのは結構大変でした。

私としてはちゃんとしたデータ解析の講習を受けるのが初めてでしたし、SQLを体系的に学んだのも初めてだったので、これはいい経験になりました。 

職場ではデータ解析の相談をできる人がいないので、ここで知り合った講師の先生や受講生の皆さんにオシゴトの相談を（守秘義務の範囲内で）したりしてます。

## 3．応用情報技術者試験を受けた

~~ちなみに落ちました~~

2．で紹介した講習会を受けているうちに、せっかく学んだことをなんらかの形で定着させたりスキル証明に使えるようにしたいと思って、勢いでAPを受験しました。 試験対策として

1.  参考書を読む（みんな大好きキタミ本を購入しました）
2.  通勤中にYoutubeの1問1答動画を流し見
3.  午後問題を読む＆スマホアプリで午前対策
4.  過去問2周ぐらい

みたいな雑な勉強法をやったせいで、午前対策はちゃんとできたのですが午後対策がほとんどできず、見事に午後落ちしました。（午前は75％取れました）

今となっては、早い段階から「[応用情報技術者試験ドットコム](https://www.ap-siken.com/)」様で問題演習を行うべきだったということと、午後対策にもっと重きを置くべきだったというのが反省点です。

とはいえ、Youtubeの流し見は意外と知識が定着したので、これ自体はそんなに悪くなかった気はします。（試験範囲を網羅しているわけではないので過信は禁物ですけども）

## 総括

他にも、ミニPC導入してみたり、L2スイッチ入れてみたりという細かなものはあるのですが、こういうのは~~誰でもやるだろう~~と思ったので割愛しました。

今年は自分の興味のある分野を押し広げた1年だったと思いますし、少々背伸びし過ぎなところもありましたが、飛び込んでみてよかったなと思いました。2025年も楽しく幸せな逸般的生活ができることを願っております。

皆様におかれましても、来る年が良い年でありますように。

## おまけ
2023年にはこんなものを書いていました。

[バイオインフォマティクスは結構エンジニア的だという話](https://epsilonminder.github.io/Mistems_advend2023/)
